In [2]:
import pandas as pd
import glob as glob
import numpy as np
!pip install geopandas
import geopandas as gpd
import matplotlib.pyplot as plt
import seaborn as sns

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting geopandas
  Downloading geopandas-0.12.2-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 20.0 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.8/dist-packages (from geopandas) (1.3.5)
Collecting fiona>=1.8
  Downloading Fiona-1.9.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 60.1 MB/s eta 0:00:00
Collecting pyproj>=2.6.1.post1
  Downloading pyproj-3.4.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 68.6 MB/s eta 0:00:00
Requirement already satisfied: packaging in /usr/local/lib/python3.8/dist-packages (from geopandas) (23.0)
Requirement already satisfied: shapely>=1.7 in /usr/local/lib/python3.8/dist-packages (from geopandas) (2.0.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.8/dist-packages (from fiona>=1.8->geopandas) (2022.12.7)
Collecting click~=8.0
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 KB 13.3 MB/s eta 0:00:00
Collecting cligj>=0.5
  Downloading cligj-0.7.2-py3-none-any.whl (7.1 kB)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.8/dist-packages (from fiona>=1.8->geopandas) (22.2.0)
Collecting click-plugins>=1.0
  Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/dist-packages (from fiona>=1.8->geopandas) (57.4.0)
Collecting munch>=2.3.2
  Downloading munch-2.5.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.0.0->geopandas) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.0.0->geopandas) (1.22.4)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.0.0->geopandas) (2022.7.1)
Requirement already satisfied: six in /usr/local/lib/python3.8/dist-packages (from munch>=2.3.2->fiona>=1.8->geopandas) (1.15.0)
Installing collected packages: pyproj, munch, click, cligj, click-plugins, fiona, geopandas
  Attempting uninstall: click
    Found existing installation: click 7.1.2
    Uninstalling click-7.1.2:
      Successfully uninstalled click-7.1.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask 1.1.4 requires click<8.0,>=5.1, but you have click 8.1.3 which is incompatible.
Successfully installed click-8.1.3 click-plugins-1.1.1 cligj-0.7.2 fiona-1.9.1 geopandas-0.12.2 munch-2.5.0 pyproj-3.4.1

In [3]:
df_jams = pd.read_csv("/content/drive/MyDrive/Mini DS/aggregate_median_jams_Kota Depok.csv")
df_alerts = pd.read_csv("/content/drive/MyDrive/Mini DS/aggregate_alerts_Kota Depok.csv")
df_irre = pd.read_csv("/content/drive/MyDrive/Mini DS/aggregate_median_jams_Kota Depok.csv")
public_holiday = pd.read_csv("/content/drive/MyDrive/Mini DS/holiday.txt",
                             sep='\t')

df_jams.drop("Unnamed: 0", axis=1, inplace=True)

In [4]:
df_jams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157218 entries, 0 to 157217
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   time                       157218 non-null  object
 1   kemendagri_kabupaten_kode  157218 non-null  float64
 2   kemendagri_kabupaten_nama  157218 non-null  object
 3   street                     154459 non-null  object
 4   level                      157218 non-null  int64
 5   median_length              157218 non-null  float64
 6   median_delay               157218 non-null  float64
 7   median_speed_kmh           157218 non-null  float64
 8   total_records              157218 non-null  int64
 9   id                         157218 non-null  int64
 10  date                       157218 non-null  object
 11  median_level               157218 non-null  float64
 12  geometry                   157218 non-null  object
dtypes: float64(5), int64(3), object(5)
memory usage: 15.6+ MB

In [5]:
df_jams.sample(5)

,time,kemendagri_kabupaten_kode,kemendagri_kabupaten_nama,street,level,median_length,median_delay,median_speed_kmh,total_records,id,date,median_level,geometry
68707,2022-08-01 18:00:00.000,32.76,KOTA DEPOK,Exit Cisalak/Pasar Rebo/Cibinong,4,554.0,541.0,3.595000,58,35171571,2022-08-01,4.0,"MULTILINESTRING ((106.871883 -6.382283, 106.87..."
42632,2022-07-23 09:00:00.000,32.76,KOTA DEPOK,Surya Kencana,2,449.0,76.0,11.850000,1,34586926,2022-07-23,2.0,"LINESTRING (106.733466 -6.358295, 106.733512 -..."
47490,2022-07-24 19:00:00.000,32.76,KOTA DEPOK,Curug Agung,3,536.0,93.0,10.559999,10,34662945,2022-07-24,3.0,"MULTILINESTRING ((106.80246 -6.368939, 106.801..."
150501,2022-09-03 08:00:00.000,32.76,KOTA DEPOK,Pondok Labu Raya,1,445.0,63.0,11.310000,2,37166890,2022-09-03,1.0,"LINESTRING (106.793057 -6.315614, 106.793099 -..."
133905,2022-08-28 03:00:00.000,32.76,KOTA DEPOK,Tole Iskandar,2,1273.0,111.0,18.290000,3,36802300,2022-08-28,2.0,"MULTILINESTRING ((106.847357 -6.404951, 106.84..."

In [6]:
df_jams.isna().sum()

time                            0
kemendagri_kabupaten_kode       0
kemendagri_kabupaten_nama       0
street                       2759
level                           0
median_length                   0
median_delay                    0
median_speed_kmh                0
total_records                   0
id                              0
date                            0
median_level                    0
geometry                        0
dtype: int64

In [7]:
df_jams.duplicated().sum()

0

In [8]:
df_jams.dropna(subset=['street'], axis=0, inplace=True)

In [11]:
df_alerts.isna().sum()

id                             0
time                           0
kemendagri_kabupaten_kode      0
kemendagri_kabupaten_nama      0
street                       500
type                           0
avg_location                   0
total_records                  0
date                           0
dtype: int64

In [ ]:
df_alerts.sample(5)

In [10]:
df_alerts = df_alerts[df_alerts['type']=='JAM'].copy()

In [12]:
df_alerts.shape

(11753, 9)

In [13]:
df_irre.sample(5)

,Unnamed: 0,time,kemendagri_kabupaten_kode,kemendagri_kabupaten_nama,street,level,median_length,median_delay,median_speed_kmh,total_records,id,date,median_level,geometry
39811,39811,2022-07-22 04:00:00.000,32.76,KOTA DEPOK,Citayam Raya,4,409.0,117.0,8.855,8,34509188,2022-07-22,4.0,"MULTILINESTRING ((106.805932 -6.440817, 106.80..."
133783,53955,2022-08-27 22:00:00.000,32.76,KOTA DEPOK,NaN,2,223.0,76.0,5.310,9,36733541,2022-08-27,2.0,"MULTILINESTRING ((106.857501 -6.446154, 106.85..."
139596,59768,2022-08-30 06:00:00.000,32.76,KOTA DEPOK,Pondok Labu Raya,2,445.0,67.5,10.980,2,36915133,2022-08-30,2.0,"LINESTRING (106.793057 -6.315614, 106.793099 -..."
118939,39111,2022-08-22 09:00:00.000,32.76,KOTA DEPOK,Nusantara,2,848.0,76.5,18.515,28,36434489,2022-08-22,2.0,"MULTILINESTRING ((106.814322 -6.389676, 106.81..."
63968,63968,2022-07-30 21:00:00.000,32.76,KOTA DEPOK,Mohammad Kahfi 2,2,1607.0,180.0,15.620,13,35043578,2022-07-30,2.0,"MULTILINESTRING ((106.812544 -6.350333, 106.81..."

In [14]:
public_holiday

            Date    Weekday            Note              Holiday
0   Jan 01, 2022   Saturday  Public Holiday       New Year's Day
1   Feb 01, 2022    Tuesday  Public Holiday     Chinese New Year
2   Feb 28, 2022     Monday  Public Holiday      Isra and Mi'raj
3   Mar 03, 2022   Thursday  Public Holiday                Nyepi
4   Apr 15, 2022     Friday  Public Holiday          Good Friday
5   May 01, 2022     Sunday  Public Holiday            Labor Day
6   May 02, 2022     Monday  Public Holiday          Eid al-Fitr
7   May 03, 2022    Tuesday  Public Holiday  Eid al-Fitr Holiday
8   May 16, 2022     Monday  Public Holiday           Buddha Day
9   May 26, 2022   Thursday  Public Holiday        Ascension Day
10  Jun 01, 2022  Wednesday  Public Holiday        Pancasila Day
11  Jul 09, 2022   Saturday  Public Holiday          Eid al-Adha
12  Jul 30, 2022   Saturday  Public Holiday     Islamic New Year
13  Aug 17, 2022  Wednesday  Public Holiday     Independence Day
14  Oct 08, 2022   Saturday  Public Holiday   Prophet's Birthday
15  Dec 25, 2022     Sunday  Public Holiday        Christmas Day

In [15]:
public_holiday.rename(columns={"Date":"time"}, inplace=True)
public_holiday['time'] = pd.to_datetime(public_holiday["time"], format='%b %d, %Y') #reformating date

In [16]:
public_holiday.sample(5)

         time   Weekday            Note           Holiday
8  2022-05-16    Monday  Public Holiday        Buddha Day
12 2022-07-30  Saturday  Public Holiday  Islamic New Year
9  2022-05-26  Thursday  Public Holiday     Ascension Day
15 2022-12-25    Sunday  Public Holiday     Christmas Day
5  2022-05-01    Sunday  Public Holiday         Labor Day

In [17]:
df_jams['time'] = pd.to_datetime(df_jams['time'], format="%Y-%m-%d %H:%M:%S.%f")

In [18]:
df_jams['day_name'] = df_jams['time'].dt.day_name()
df_jams['hour'] = df_jams['time'].dt.hour
df_jams['weekday'] = df_jams['time'].dt.weekday
df_jams['isweekend'] = np.where(((df_jams['weekday']==5) | (df_jams['weekday']==6)),
                                1,0)
df_jams['month'] = df_jams['time'].dt.month
df_jams['pub_holiday'] = np.where((df_jams['time'].dt.date.astype(str)).isin(public_holiday['time'].astype(str)),
                                  1,0)

df_jams.sample(5)

,time,kemendagri_kabupaten_kode,kemendagri_kabupaten_nama,street,level,median_length,median_delay,median_speed_kmh,total_records,id,date,median_level,geometry,day_name,hour,weekday,isweekend,month,pub_holiday
151482,2022-09-03 12:00:00,32.76,KOTA DEPOK,Pahlawan,3,218.0,112.0,4.96,11,37167771,2022-09-03,3.0,"MULTILINESTRING ((106.751205 -6.366154, 106.75...",Saturday,12,5,1,9,0
133749,2022-08-27 21:00:00,32.76,KOTA DEPOK,Lenteng Agung Timur,2,870.0,98.0,18.44,1,36733382,2022-08-27,2.0,"LINESTRING (106.834658 -6.338447, 106.834402 -...",Saturday,21,5,1,8,0
37801,2022-07-21 07:00:00,32.76,KOTA DEPOK,Gandul Raya,2,836.0,119.0,13.38,7,34450483,2022-07-21,2.0,"MULTILINESTRING ((106.793171 -6.340327, 106.79...",Thursday,7,3,0,7,0
46596,2022-07-24 14:00:00,32.76,KOTA DEPOK,Sawangan Permai,3,190.0,84.0,5.57,13,34662099,2022-07-24,3.0,"MULTILINESTRING ((106.772422 -6.403528, 106.77...",Sunday,14,6,1,7,0
125881,2022-08-25 08:00:00,32.76,KOTA DEPOK,Karang Tengah 1,4,208.0,126.0,4.70,2,36593935,2022-08-25,4.0,"LINESTRING (106.784083 -6.311092, 106.784238 -...",Thursday,8,3,0,8,0

In [20]:
df_jams.to_parquet('/content/drive/MyDrive/Mini DS', index=False)

IsADirectoryError: ignored